# Generated by Django 5.0.1 on 2024-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_ad_spend', models.IntegerField()),
                ('Avg_cpc', models.IntegerField()),
                ('Avg_cost_per_conversion', models.IntegerField()),
                ('Total_revenue', models.IntegerField()),
                ('data', models.FileField(upload_to='csv_files')),
            ],
        ),
    ]
