# Generated by Django 5.0.1 on 2024-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_googledata_date_alter_googledata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
