# Generated by Django 5.0.1 on 2024-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0003_alter_googledata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledata',
            name='date',
            field=models.DateField(),
        ),
    ]
