# Generated by Django 5.0.1 on 2024-01-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_rename_date_googledata_today_alter_googledata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledata',
            name='Avg_cost_per_conversion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='googledata',
            name='Avg_cpc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='googledata',
            name='Total_ad_spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='googledata',
            name='Total_revenue',
            field=models.FloatField(),
        ),
    ]
